import React from 'react'

function About() {
  return (
    <div className=' mt-16 text-3xl w-[200px] h-[200px] bg-green-500'>
      Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ullam dolorem quisquam architecto, nulla eaque iure. Odio natus obcaecati laboriosam deserunt aliquid harum consequuntur cumque fugiat, alias corporis aspernatur quibusdam possimus voluptas quidem et magni illum officia autem recusandae. Quas fuga reprehenderit repellat distinctio laudantium cum, excepturi non dolorum! Expedita omnis iure amet similique quia a iste, magnam eos porro laudantium consequatur blanditiis magni repellendus, sapiente perferendis est quas doloremque facere quasi numquam nesciunt optio ipsam accusamus? Dolore blanditiis ipsa error ullam dolores reprehenderit ut aliquam dignissimos dolor eum nobis, debitis exercitationem, vitae sint animi perspiciatis, voluptas cumque! Aspernatur non labore velit natus ab voluptate omnis suscipit dolor, cumque porro similique! Sapiente corporis minus inventore dolores? Non quisquam mollitia a quam aliquam magni voluptas, laboriosam harum odit quod molestiae reiciendis? Cum eveniet, voluptatibus nobis tempora ab, nulla consectetur veniam reprehenderit impedit aspernatur repellat possimus, rem quos modi fugit soluta nihil! Non, iure atque. Autem commodi nihil ab laboriosam nobis vero natus deserunt dignissimos deleniti! Et corporis amet necessitatibus magnam aliquam, deserunt velit expedita nobis consequatur accusantium sapiente ipsa? Qui minus placeat aut laudantium, culpa deleniti, id corporis ducimus earum tempora et modi exercitationem! Rem laboriosam dolor eum autem hic commodi laudantium quas mollitia illo. Adipisci enim aspernatur, repellendus laudantium deleniti ratione quam blanditiis, molestias impedit perferendis cumque esse laborum amet inventore perspiciatis, commodi vitae at voluptas eius? Soluta provident velit quod inventore? Doloremque tempora quibusdam consectetur eos quam. Quos facilis expedita, dolore voluptates enim beatae soluta nemo molestiae saepe aliquam pariatur tenetur voluptatum debitis tempore fugit fuga eos amet voluptatem vitae natus iste ratione delectus vel! Nobis rem quidem numquam autem et beatae libero inventore alias voluptate soluta. Cupiditate, consequuntur deserunt ad repellendus eaque fugiat quas assumenda atque neque eius, necessitatibus maxime doloribus quaerat nostrum, explicabo exercitationem. Sequi quam porro beatae.
    </div>
  )
}

export default About
